// Converts the Hershey "futural" (Roman Simplex) .jhf font into src/lib/hersheyData.ts.
// Each glyph is stored as its raw Hurt-format string: first pair = left/right bearing,
// following pairs = coordinates offset by 'R', " R" = pen up.
import { readFileSync, writeFileSync } from 'node:fs';
const raw = readFileSync(new URL('./futural.jhf', import.meta.url), 'utf8').split(/\r?\n/);
const glyphs = [];
let i = 0;
while (i < raw.length) {
  let line = raw[i++];
  if (!line.trim()) continue;
  const n = parseInt(line.slice(5, 8), 10);
  let data = line.slice(8);
  while (data.length < n * 2 && i < raw.length) data += raw[i++];
  glyphs.push(data.slice(0, n * 2));
}
if (glyphs.length < 95) throw new Error(`expected 95+ glyphs, got ${glyphs.length}`);
glyphs.length = 95; // drop the DEL filler glyph
const out = `/*
 * Hershey Roman Simplex (futural) single-stroke font, ASCII 32..126.
 * Generated by scripts/build-hershey.mjs — do not edit.
 *
 * The Hershey Fonts were originally created by Dr. A. V. Hershey while working
 * at the U. S. National Bureau of Standards.
 * The format of the Font data in this distribution was originally created by
 * James Hurt, Cognition, Inc., 900 Technology Park Drive, Billerica, MA 01821
 * (mit-eddie!ci-dandelion!hurt)
 */
export const HERSHEY_SIMPLEX: readonly string[] = ${JSON.stringify(glyphs, null, 0).replace(/","/g, '",\n  "').replace('["', '[\n  "').replace(/"]$/, '",\n]')};
`;
writeFileSync(new URL('../src/lib/hersheyData.ts', import.meta.url), out);
console.log('wrote', glyphs.length, 'glyphs');
